version: '3'
services:
    database:
        image: mariadb
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=test
            - MYSQL_USER=admin

