#!/usr/bin/env node
/*
 *  Github/TonyChG
 *  index.js
 *  Description:
**/

// Specify root dir
require('app-module-path').addPath(__dirname);

const config = require('config');

// Import classes
const Command = require('lib/command');
const Client = require('lib/client');
const Backup = require('lib/backup');
const Manager = require('lib/manager');

async function main() {

    const cmd = new Command(process.argv);
    const manager = new Manager(cmd.options);

    try {
        await manager.loadDatabases();
        await manager.start();
        manager.quit();
    } catch (e) {
        manager.quit(e);
    }
}

main();
