#!/usr/bin/env node
/*
 *  Github/TonyChG
 *  index.js
 *  Description:
**/

// Specify root dir
require('app-module-path').addPath(__dirname);

const config = require('config');

// Import classes
const Command = require('lib/command');
const Client = require('lib/client');
const Backup = require('lib/backup');

async function main() {
    const schemaTest = new Client({
        host: '127.0.0.1',
        user: 'root',
        password: 'root',
        database: 'phonik001'
    });

    try {
        await schemaTest.init();

        const backupTest = new Backup(schemaTest);
        // await backupTest.save();

        await backupTest.restore('./backups/phonik001_31-2-2018-19-23-16.tar.gz');
        // console.log(await schema.fetchTables());
        process.exit(0);
    } catch (e) {
        console.error(e.message);
        process.exit(42);
    }
}

main();
