#!/usr/bin/env node
/*
 *  Github/TonyChG
 *  index.js
 *  Description:
**/

// Specify root dir
require('app-module-path').addPath(__dirname);

const config = require('config');

// Import classes
const Command = require('lib/command');
const Client = require('lib/client');
const Backup = require('lib/backup');
const Manager = require('lib/manager');

async function main() {

    const cmd = new Command(process.argv);
    const manager = new Manager(cmd.options);

    try {
        await manager.loadDatabases();
        await manager.start();
    } catch (e) {
        manager.quit(e);
    }
    // const schemaTest = new Client({
    //     ...config.database.connection,
    //     database: 'pc-expert'
    // });
    //
    // try {
    //     await schemaTest.init();
    //
    //     const backupTest = new Backup(schemaTest);
    //     await backupTest.save();
    //
    //     // await backupTest.restore('./backups/pc-expert_31-2-2018-19-43-23.tar.gz');
    //     process.exit(0);
    // } catch (e) {
    //     console.error(e.message);
    //     process.exit(42);
    // }
}

main();
