DROP TABLE IF EXISTS `users`;

CREATE TABLE `users` (
  `id` mediumint(8) unsigned NOT NULL auto_increment,
  `name` varchar(255) default NULL,
  `email` varchar(255) default NULL,
  PRIMARY KEY (`id`)
) AUTO_INCREMENT=1;

INSERT INTO `users` (`name`,`email`) VALUES ("Lœle Duke","nec.ante@vitaevelitegestas.edu"),("Steven Cervantes","convallis@tellus.co.uk"),("Kelly Bishop","aliquet.magna@arcuSed.com"),("Chase Martinez","erat.eget@velit.ca"),("Wallace Chan","Curabitur@semper.co.uk"),("Derek Trujillo","lectus@Craseu.co.uk"),("Emmanuel Barber","risus.Donec@ornarelectus.co.uk"),("Tucker Buck","id@egestas.org"),("Brenden Rivers","leo.elementum.sem@diam.net"),("Hammett Alford","sem@condimentum.org");
INSERT INTO `users` (`name`,`email`) VALUES ("Brent Calderon","nisl.Quisque.fringilla@tristique.co.uk"),("Camden Dudley","imperdiet@et.net"),("Martin Reid","sapien.imperdiet.ornare@nibhenim.edu"),("Knox Poole","auctor.nunc.nulla@lectuspede.org"),("Kane Cook","congue.In@posuereenimnisl.org"),("Jasper Murray","ac@nislQuisquefringilla.net"),("Keegan Francis","placerat.velit@ultrices.net"),("Chandler Haney","Curae.Donec.tincidunt@at.ca"),("Jordan Adkins","Pellentesque.habitant.morbi@auctor.com"),("Ryder Park","feugiat.metus@tellusidnunc.org");
INSERT INTO `users` (`name`,`email`) VALUES ("Damian Wolf","vel.mauris.Integer@sitamet.com"),("Sawyer Stanley","tellus.sem.mollis@faucibusMorbivehicula.org"),("Malik Knox","Suspendisse.tristique@arcuiaculisenim.org"),("Porter Maxwell","augue.id.ante@semelitpharetra.ca"),("Ethan Mccray","placerat@amet.ca"),("Lane Barnett","In.condimentum.Donec@pellentesque.ca"),("Price Flores","gravida@aenim.ca"),("Reuben Austin","habitant.morbi.tristique@antedictummi.ca"),("Hammett Levy","arcu@dictum.edu"),("Lars Pacheco","arcu@metusAenean.edu");
INSERT INTO `users` (`name`,`email`) VALUES ("Ronan Mcclain","Mauris@velitin.edu"),("Cairo Holder","Quisque.ac@lobortis.net"),("Kennan Brock","a.purus.Duis@magnis.co.uk"),("Troy Guzman","erat.semper@libero.co.uk"),("Simon Hewitt","Donec@pellentesqueSeddictum.com"),("Vernon Boyd","tortor.Nunc@eu.edu"),("Brody Velez","purus.in.molestie@pellentesqueSed.net"),("Merrill Woodward","ipsum.ac@Duiscursusdiam.net"),("Phelan Wilder","tellus.Nunc.lectus@vitae.net"),("Garrett Frank","Nunc.pulvinar@sapien.co.uk");
INSERT INTO `users` (`name`,`email`) VALUES ("Oleg Burke","eget.ipsum.Suspendisse@elitelit.com"),("Lyle Sykes","ligula@egestasa.edu"),("Amery Crane","metus@egestaslacinia.ca"),("Burton Blankenship","Donec.est.Nunc@justoPraesentluctus.com"),("Lee Vega","feugiat@vulputateduinec.net"),("Derek Hyde","vel.sapien@molestie.org"),("Alexander Guzman","dui.Fusce@arcuSedeu.edu"),("Abdul Valentine","elit.Etiam.laoreet@ultricesDuisvolutpat.co.uk"),("Jin Forbes","erat.volutpat.Nulla@habitant.edu"),("Carter Ross","purus.in@hendrerit.co.uk");
INSERT INTO `users` (`name`,`email`) VALUES ("Luke Ramsey","Curae@ametconsectetueradipiscing.org"),("Tanner Odonnell","convallis.convallis.dolor@Donec.net"),("Amal Welch","sapien@urnaconvallis.com"),("Preston Mason","eu.tellus@nec.ca"),("Honorato Stark","non.bibendum.sed@elit.org"),("Dean Hubbard","velit.Aliquam.nisl@diam.co.uk"),("Reuben Mclaughlin","consectetuer@tristique.ca"),("Kuame Hansen","aliquet.libero.Integer@eu.ca"),("Bradley Beasley","nulla@urnasuscipit.co.uk"),("Lawrence Barnett","Proin.vel.nisl@feugiatplacerat.edu");
INSERT INTO `users` (`name`,`email`) VALUES ("Bruce Hicks","a@Nunc.ca"),("Dylan Berger","magnis.dis.parturient@ataugueid.ca"),("Ignatius Valentine","interdum@magnaPhasellus.ca"),("Gary Zamora","magna.malesuada@aceleifend.ca"),("Abraham Pennington","Donec.porttitor@Cumsociis.com"),("Mufutau Mcmahon","porttitor@Cras.edu"),("Kyle Carey","velit.Quisque@etrutrumeu.org"),("Rogan Haley","amet.faucibus.ut@vitaediamProin.org"),("Dieter Norman","ullamcorper.magna@lacus.org"),("Uriel Marshall","ante.dictum.mi@Nuncmauris.co.uk");
INSERT INTO `users` (`name`,`email`) VALUES ("Magee Ross","adipiscing@mauris.net"),("Thomas Nicholson","pretium@liberoProin.org"),("Mark Mcfadden","nibh.Aliquam.ornare@velvulputateeu.edu"),("Arden Trevino","Sed@AeneanmassaInteger.org"),("Plato Larsen","vitae.aliquet@lacusUtnec.net"),("Jameson Soto","ultricies.dignissim.lacus@commodoatlibero.edu"),("Marvin Hayes","lorem@cursus.ca"),("Eric Barlow","netus.et.malesuada@loremauctorquis.com"),("Clark Wynn","dignissim.lacus.Aliquam@duiquis.org"),("Ethan Swanson","vel.arcu.eu@odioapurus.edu");
INSERT INTO `users` (`name`,`email`) VALUES ("Fitzgerald Booth","ullamcorper.magna@Integeraliquamadipiscing.com"),("Graiden Larson","Nulla.eget@laoreet.net"),("Joseph Beasley","volutpat@lectusCumsociis.com"),("Honorato Cruz","egestas.nunc.sed@necante.edu"),("Randall Castro","est@convallis.co.uk"),("Eaton Burris","scelerisque.sed.sapien@mattis.ca"),("Tanek Hopkins","purus.Duis.elementum@odiosemper.edu"),("Yardley Wynn","Nulla.interdum.Curabitur@aodio.edu"),("Rooney Pearson","Cras.eu.tellus@mollis.edu"),("Lionel Mayer","mattis.Cras@rutrumjustoPraesent.com");
INSERT INTO `users` (`name`,`email`) VALUES ("Porter Floyd","odio@massalobortisultrices.org"),("Jeremy Mills","commodo@Phasellusliberomauris.ca"),("Vladimir Rosa","semper@arcuAliquamultrices.com"),("Dennis Bell","vitae.mauris@massanon.org"),("Kyle Franklin","Praesent@tempus.com"),("Joseph Head","amet.ornare.lectus@Aliquamadipiscinglobortis.edu"),("Yasir Mills","nec@quamdignissimpharetra.net"),("Perry Horne","nibh.Quisque@blanditmattisCras.org"),("Bruno Guy","et@acmattissemper.edu"),("Burke Todd","Nullam@aliquetlibero.com");

